name: Release REST API

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get-version.outputs.version-without-v }}
    steps:
      - uses: actions/checkout@v5
      - id: get-version
        uses: battila7/get-version-action@v2.3.0
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: REST API ${{ steps.get-version.outputs.version-without-v }}
          draft: false
          prerelease: false

  upload-assets:
    name: Build and upload ${{ matrix.arch }}
    needs: create-release
    strategy:
      matrix:
        include:
          - arch: linux-amd64
            runner: ubuntu-latest
          - arch: linux-arm64
            runner: ubuntu-latest-arm64-small
    runs-on: ${{ matrix.runner }}
    env:
      MVN: ./mvnw --show-version --batch-mode --no-transfer-progress
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 25
          distribution: graalvm
          cache: maven
      - run: $MVN -DskipTests package -Pnative
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/model-graph-rest-api-${{ needs.create-release.outputs.version }}-runner
          asset_name: ${{ github.event.repository.name }}-${{ needs.create-release.outputs.version }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
